-- Unit tests for the inline-SVG namespacing (issue #27).
-- Run from the repo root:   pandoc lua tests/test_inline_svg.lua

dofile('_extensions/tikz/tikz.lua')
local N = TIKZ_TEST.namespace_svg
local t = dofile('tests/harness.lua')
local check = t.check
local has = t.has

-- The prolog, DOCTYPE and generator comments are a document's furniture and
-- must not survive into an HTML page.
local pro = "<?xml version='1.0'?>\n<!-- generated by dvisvgm -->\n<svg width='1'></svg>"
check('prolog stripped', has(N(pro, 'n1'), '<?xml'), false)
check('comment stripped', has(N(pro, 'n1'), 'dvisvgm'), false)
check('starts at the root', N(pro, 'n1'):sub(1, 4), '<svg')
check('no <svg> root is reported', N('<html></html>', 'n1'), nil)

-- pdftocairo: ids referenced through xlink:href and url(). Both forms must
-- move with the id, or a second diagram on the page steals the definitions.
local cairo = [[<svg><defs><clipPath id="clip-0"><path id="glyph-0-0"/></clipPath></defs>]] ..
              [[<g clip-path="url(#clip-0)"><use xlink:href="#glyph-0-0"/></g></svg>]]
local c = N(cairo, 'tikz7')
check('id renamed', has(c, 'id="clip-0-tikz7"'), true)
check('url() reference follows', has(c, 'url(#clip-0-tikz7)'), true)
check('xlink:href follows', has(c, 'xlink:href="#glyph-0-0-tikz7"'), true)
check('no bare id left', has(c, 'id="clip-0"'), false)
check('no bare reference left', has(c, 'url(#clip-0)'), false)

-- A hyphenated id is the case that first broke this: pat_escape turns
-- 'glyph-0-0' into 'glyph%-0%-0', which is invalid as a replacement string.
check('hyphenated ids survive escaping', has(c, 'glyph-0-0-tikz7'), true)

-- An id that is a prefix of another must not be partially rewritten.
local pre = [[<svg><path id="a"/><path id="ab"/><use href="#ab"/></svg>]]
local p = N(pre, 'n')
check('prefix id not clobbered', has(p, 'id="ab-n"'), true)
check('prefix reference intact', has(p, 'href="#ab-n"'), true)

-- dvisvgm: CSS class names and @font-face families are page-global too.
local dvi = [[<svg><style>@font-face{font-family:cmmi10;src:url(data:x)}]] ..
            [[text.f0 {font-family:cmmi10;font-size:9.9px}</style>]] ..
            [[<text class='f0'>W</text></svg>]]
local d = N(dvi, 'tikz2')
check('class attribute renamed', has(d, "class='f0-tikz2'"), true)
check('class selector renamed', has(d, 'text.f0-tikz2 {'), true)
check('@font-face family renamed', has(d, 'font-family:cmmi10-tikz2;src:'), true)
check('family use renamed', has(d, 'font-family:cmmi10-tikz2;font-size:'), true)
check('no bare family left', has(d, 'font-family:cmmi10;'), false)

-- Two diagrams namespaced differently must share no names at all.
local one, two = N(dvi, 'tikz1'), N(dvi, 'tikz2')
check('nonces separate the two', one ~= two, true)
check('first has no second-nonce name', has(one, 'tikz2'), false)

-- Styling hook and accessible name.
check('root gains a class hook', has(N(dvi, 'n'), '<svg class="tikz-svg"'), true)
check('alt becomes a <title>',
  has(N(dvi, 'n', 'A causal diagram'), '<title>A causal diagram</title>'), true)
check('no <title> without alt', has(N(dvi, 'n'), '<title>'), false)
check('title text is escaped',
  has(N(dvi, 'n', 'a < b & c'), '<title>a &lt; b &amp; c</title>'), true)
-- A class already on the root is namespaced like any other (its own
-- stylesheet may select on it), and the hook is appended rather than lost.
local kept = N([[<svg class="keep"></svg>]], 'n')
check('existing root class is namespaced', has(kept, 'keep-n'), true)
check('hook appended alongside it', has(kept, 'class="keep-n tikz-svg"'), true)

-- as_figure: every renderer ends the same way. Three produce a RawBlock,
-- which Figure takes directly; the <img> path produces an Image, which is an
-- Inline and needs a Plain around it. Four copies of this used to say so
-- separately.
local F = TIKZ_TEST.as_figure
local RAW = pandoc.RawBlock('html', '<svg/>')
local IMG = pandoc.Image({}, 'x.svg')
local CAP = pandoc.read('A caption.', 'markdown').blocks

check('uncaptioned raw block is emitted bare',
  F(RAW, {caption = nil, ['fig-attr'] = {}}).t, 'RawBlock')
check('uncaptioned image is wrapped in a Plain',
  F(IMG, {caption = nil, ['fig-attr'] = {}}).t, 'Plain')
local fig = F(RAW, {caption = CAP, ['fig-attr'] = {id = 'fig-x'}})
check('captioned raw block becomes a Figure', fig.t, 'Figure')
check('…carrying the fig-attr id', fig.identifier, 'fig-x')
check('…and the caption', pandoc.utils.stringify(fig.caption), 'A caption.')
check('…with the raw block as its content', fig.content[1].t, 'RawBlock')
fig = F(IMG, {caption = CAP, ['fig-attr'] = {id = 'fig-y'}})
check('captioned image becomes a Figure', fig.t, 'Figure')
check('…with the image inside a Plain', fig.content[1].t, 'Plain')
check('…still an Image within it', fig.content[1].content[1].t, 'Image')

t.done()
