-- Unit tests for the inline-SVG namespacing (issue #27).
-- Run from the repo root:   pandoc lua tests/test_inline_svg.lua

dofile('_extensions/tikz/tikz.lua')
local N = TIKZ_TEST.namespace_svg
local t = dofile('tests/harness.lua')
local check = t.check
local has = t.has

-- The prolog, DOCTYPE and generator comments are a document's furniture and
-- must not survive into an HTML page.
local pro = "<?xml version='1.0'?>\n<!-- generated by dvisvgm -->\n<svg width='1'></svg>"
check('prolog stripped', has(N(pro, 'n1'), '<?xml'), false)
check('comment stripped', has(N(pro, 'n1'), 'dvisvgm'), false)
check('starts at the root', N(pro, 'n1'):sub(1, 4), '<svg')
check('no <svg> root is reported', N('<html></html>', 'n1'), nil)

-- pdftocairo: ids referenced through xlink:href and url(). Both forms must
-- move with the id, or a second diagram on the page steals the definitions.
local cairo = [[<svg><defs><clipPath id="clip-0"><path id="glyph-0-0"/></clipPath></defs>]] ..
              [[<g clip-path="url(#clip-0)"><use xlink:href="#glyph-0-0"/></g></svg>]]
local c = N(cairo, 'tikz7')
check('id renamed', has(c, 'id="clip-0-tikz7"'), true)
check('url() reference follows', has(c, 'url(#clip-0-tikz7)'), true)
check('xlink:href follows', has(c, 'xlink:href="#glyph-0-0-tikz7"'), true)
check('no bare id left', has(c, 'id="clip-0"'), false)
check('no bare reference left', has(c, 'url(#clip-0)'), false)

-- A hyphenated id is the case that first broke this: pat_escape turns
-- 'glyph-0-0' into 'glyph%-0%-0', which is invalid as a replacement string.
check('hyphenated ids survive escaping', has(c, 'glyph-0-0-tikz7'), true)

-- An id that is a prefix of another must not be partially rewritten.
local pre = [[<svg><path id="a"/><path id="ab"/><use href="#ab"/></svg>]]
local p = N(pre, 'n')
check('prefix id not clobbered', has(p, 'id="ab-n"'), true)
check('prefix reference intact', has(p, 'href="#ab-n"'), true)

-- dvisvgm: CSS class names and @font-face families are page-global too.
local dvi = [[<svg><style>@font-face{font-family:cmmi10;src:url(data:x)}]] ..
            [[text.f0 {font-family:cmmi10;font-size:9.9px}</style>]] ..
            [[<text class='f0'>W</text></svg>]]
local d = N(dvi, 'tikz2')
check('class attribute renamed', has(d, "class='f0-tikz2'"), true)
check('class selector renamed', has(d, 'text.f0-tikz2 {'), true)
check('@font-face family renamed', has(d, 'font-family:cmmi10-tikz2;src:'), true)
check('family use renamed', has(d, 'font-family:cmmi10-tikz2;font-size:'), true)
check('no bare family left', has(d, 'font-family:cmmi10;'), false)

-- Two diagrams namespaced differently must share no names at all.
local one, two = N(dvi, 'tikz1'), N(dvi, 'tikz2')
check('nonces separate the two', one ~= two, true)
check('first has no second-nonce name', has(one, 'tikz2'), false)

-- Styling hook and accessible name.
check('root gains a class hook', has(N(dvi, 'n'), '<svg class="tikz-svg"'), true)
check('alt becomes a <title>',
  has(N(dvi, 'n', 'A causal diagram'), '<title>A causal diagram</title>'), true)
check('no <title> without alt', has(N(dvi, 'n'), '<title>'), false)
check('title text is escaped',
  has(N(dvi, 'n', 'a < b & c'), '<title>a &lt; b &amp; c</title>'), true)
-- A class already on the root is namespaced like any other (its own
-- stylesheet may select on it), and the hook is appended rather than lost.
local kept = N([[<svg class="keep"></svg>]], 'n')
check('existing root class is namespaced', has(kept, 'keep-n'), true)
check('hook appended alongside it', has(kept, 'class="keep-n tikz-svg"'), true)

-- Selector shapes. One pattern now covers all of them; the old
-- `(%.)@(%s*{)` required the brace to follow the name, so a grouped selector
-- was skipped while the `class=` attributes it applied to were still renamed
-- — silently detaching the style from the elements.
local grouped = N([[<svg><style>.f0, .f1 {fill:red}</style><text class='f0'/><text class='f1'/></svg>]], 'n')
check('grouped selector: first name', has(grouped, '.f0-n,'), true)
check('grouped selector: second name', has(grouped, '.f1-n {'), true)
check('…and both attributes agree', has(grouped, "class='f0-n'"), true)
check('minified selector renamed',
  has(N([[<svg><style>text.f0{x:1}</style><text class='f0'/></svg>]], 'n'),
      'text.f0-n{'), true)
-- A name nothing carries is not a class, so it is left alone.
check('an unused selector name is untouched',
  has(N([[<svg><style>.ghost {x:1}</style><text class='f0'/></svg>]], 'n'),
      '.ghost '), true)
-- A decimal in path data must not be mistaken for a selector.
check('path data is not a selector',
  has(N([[<svg><style>.f0{x:1}</style><path d='M 0.5 1.2' class='f0'/></svg>]], 'n'),
      "d='M 0.5 1.2'"), true)

-- A class attribute may carry several names, so they are namespaced token by
-- token. Treating the attribute as one name meant it matched nothing at all.
local multi = N([[<svg><style>.f0 {x:1}</style><text class='f0 bold'/></svg>]], 'n')
check('every token in a class list is namespaced',
  has(multi, "class='f0-n bold-n'"), true)
check('…and the selector still agrees', has(multi, '.f0-n {'), true)

-- Rewriting is scoped to where a name can legally appear, so a name renamed
-- in one place is renamed in every other and nowhere else.

-- A `font-family` reference is terminated by the closing quote when it is the
-- last declaration in a `style="…"`. Renaming the @font-face while missing
-- that reference leaves the text asking for a family that no longer exists.
local ff = N([[<svg><style>@font-face{font-family:cmmi10;src:url(x)}</style>]] ..
             [[<text style="font-family:cmmi10">x</text></svg>]], 'n')
check('@font-face renamed', has(ff, 'font-family:cmmi10-n;src:'), true)
check('an unterminated style= reference follows',
  has(ff, 'style="font-family:cmmi10-n"'), true)
check('no bare family left anywhere', has(ff, 'font-family:cmmi10<'), false)

-- A family declared anywhere in the @font-face rule, not only first.
local late = N([[<svg><style>@font-face{src:url(x);font-family:cmmi10}</style>]] ..
               [[<text style="font-family:cmmi10;">y</text></svg>]], 'n')
check('a late font-family in @font-face is collected',
  has(late, 'font-family:cmmi10-n}'), true)
check('…and its reference follows', has(late, 'font-family:cmmi10-n;'), true)

-- A quoted family name.
local quoted = N([[<svg><style>@font-face{font-family:"cmr10";src:url(x)}]] ..
                 [[.a{font-family:"cmr10"}</style><text class="a"/></svg>]], 'n')
check('a quoted family is renamed', has(quoted, 'font-family:"cmr10-n"'), true)
check('no bare quoted family left', has(quoted, 'font-family:"cmr10"'), false)

-- A class name is a selector only in CSS. The same characters inside a
-- diagram's own label are text, and renaming them corrupts the drawing.
local label = N([[<svg><style>.f0{fill:red}</style>]] ..
                [[<text class="f0">version .f0 released</text></svg>]], 'n')
check('the selector is renamed', has(label, '.f0-n{fill:red}'), true)
check('the class attribute agrees', has(label, 'class="f0-n"'), true)
check('but the label text is left alone',
  has(label, '>version .f0 released<'), true)

-- url(#…) in a presentation attribute, outside any stylesheet.
local clip = N([[<svg><clipPath id="c0"/><g clip-path="url(#c0)"/></svg>]], 'n')
check('a presentation-attribute url() follows its id',
  has(clip, 'clip-path="url(#c0-n)"'), true)

-- The root tag. `<svg[^>]*>` stopped at the first `>` whatever it was.
local selfclosed = N([[<svg width="1"/>]], 'n', 'Alt text')
check('a self-closing root is opened up',
  has(selfclosed, '<title>Alt text</title></svg>'), true)
check('…so no self-closing root is left behind',
  has(selfclosed, '/>'), false)
local gt = N([[<svg data-x="a>b" ><g id="q"/></svg>]], 'n', 'T')
check('a > inside an attribute does not end the tag',
  has(gt, 'data-x="a>b"'), true)
check('…so the title lands after the tag, not inside it',
  has(gt, '><title>T</title>'), true)

-- Names never reach a Lua pattern, so nothing needs escaping. A literal '%'
-- in an id was the shape that broke the old double-escaping dance.
local pct = N([[<svg><g id="a%b"/><use href="#a%b"/></svg>]], 'n')
check('a percent in an id survives', has(pct, 'id="a%b-n"'), true)
check('…and its reference follows', has(pct, 'href="#a%b-n"'), true)

-- as_figure: every renderer ends the same way. Three produce a RawBlock,
-- which Figure takes directly; the <img> path produces an Image, which is an
-- Inline and needs a Plain around it.
local F = TIKZ_TEST.as_figure
local RAW = pandoc.RawBlock('html', '<svg/>')
local IMG = pandoc.Image({}, 'x.svg')
local CAP = pandoc.read('A caption.', 'markdown').blocks

check('uncaptioned raw block is emitted bare',
  F(RAW, {caption = nil, ['fig-attr'] = {}}).t, 'RawBlock')
check('uncaptioned image is wrapped in a Plain',
  F(IMG, {caption = nil, ['fig-attr'] = {}}).t, 'Plain')
local fig = F(RAW, {caption = CAP, ['fig-attr'] = {id = 'fig-x'}})
check('captioned raw block becomes a Figure', fig.t, 'Figure')
check('…carrying the fig-attr id', fig.identifier, 'fig-x')
check('…and the caption', pandoc.utils.stringify(fig.caption), 'A caption.')
check('…with the raw block as its content', fig.content[1].t, 'RawBlock')
fig = F(IMG, {caption = CAP, ['fig-attr'] = {id = 'fig-y'}})
check('captioned image becomes a Figure', fig.t, 'Figure')
check('…with the image inside a Plain', fig.content[1].t, 'Plain')
check('…still an Image within it', fig.content[1].content[1].t, 'Image')

t.done()
